name: C/C++ CI

on:
  push:
    branches: [ "tags/v22.03.3" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make
